### ISSUE TITLE
a question regarding your code

### ISSUE THREAD

**Issue by Diyorazh** [empyriumz/Entanglement-Dynamics#1]
Hi, I am a senior student major in physics. I was trying to reproduce your codes with my understanding. I found a part a little bit confusing. When you prepare then measure function, may I ask why there is a 2**(l-n-1)) dimension sparse matrix performed?

Thank you in advance for your kind response!

`            up=sparse.kron(sparse.identity(2**n),sz)
            up=sparse.kron(up,sparse.identity(2**(l-n-1)))
            up=0.5*(up+sparse.identity(2**l)) `

**Comment by empyriumz** [comment]
hi @Diyorazh, the measurement is a projective matrix which takes the form $1/2(s_z+I)$ 
And `s_z` here should be understood as the spin-z operator acting on the total many-body Hilbert space with dimension `2**l`, and `n` denotes the position to perform the measurement. 
The measurement does nothing on the rest of the system, hence the identity matrix anywhere else. 

A bit of caution: this measurement method is straightforward but very slow numerically, you should check `measure(wave, prob, pos, l)` if you want to simulate larger systems.

Hope this clarifies :)

**Comment by Diyorazh** [comment]
Hi, I am sorry I was still a little bit confused on the "**1**" in the second line. Would you like to illustrate a little bit more? Thank you!

**Comment by empyriumz** [comment]
hi @Diyorazh it's the identity matrix in this Hilbert space.
